/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-05-11 19:10:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MenuPrincipal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Jaro:opsz@6..72&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sesion:hover {\n");
      out.write("            background-color: red;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("        .cerrarSesion {\n");
      out.write("            width: 100%;    \n");
      out.write("            display: flex;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("            position: absolute;\n");
      out.write("            margin: 3vh 0 0 0;\n");
      out.write("           \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sesion {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 20%;\n");
      out.write("            padding: 1vh;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: black;\n");
      out.write("            \n");
      out.write("            margin: 0 4vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .regresar {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 20%;\n");
      out.write("            padding: 1vh;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: black;\n");
      out.write("            \n");
      out.write("            margin: 0 4vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .regresar:hover{\n");
      out.write("            background-color: greenyellow;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .contenedor {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .titulo {\n");
      out.write("            \n");
      out.write("            font-size: 20vh;\n");
      out.write("            margin: 2vh 0 10vh 0;\n");
      out.write("            font-family: \"Bebas Neue\", sans-serif;\n");
      out.write("            font-weight: 400;\n");
      out.write("            font-style: normal;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        .caja {\n");
      out.write("            \n");
      out.write("            padding: 5vh 0;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8);\n");
      out.write("            width: 70%;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-around;\n");
      out.write("            align-items: center;\n");
      out.write("            border-radius: 4vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .opciones {\n");
      out.write("            \n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .imagen {\n");
      out.write("            \n");
      out.write("            width: 30vh;\n");
      out.write("            height: 30vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .opciones a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 6vh;\n");
      out.write("            color: black;\n");
      out.write("            width: 100%;\n");
      out.write("            text-align: center;\n");
      out.write("            border-radius: 5vh;\n");
      out.write("            border: 1px solid black;\n");
      out.write("            background-color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .opciones a:hover {\n");
      out.write("            background-color: black;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script src=\"https://kit.fontawesome.com/26a3cc7edf.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body style=\"position: relative;\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");
  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");  
        if (session.getAttribute("user")==null){
            response.sendRedirect("Login.jsp");
        }
    
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <img src=\"https://png.pngtree.com/thumb_back/fw800/background/20210724/pngtree-blue-white-square-squares-superimposed-stylish-geometric-abstract-background-image_752538.jpg\" alt=\"\" style=\"position: absolute; height: 100vh; width: 100%; z-index: -1; filter: brightness(90%);\">\n");
      out.write("    <div class=\"cerrarSesion\">\n");
      out.write("        <!--<a href=\"#\" class=\"regresar\"><i class=\"fa-solid fa-circle-left\" style=\"font-size: 6vh; padding: 2vh 0;\"></i>Regresar Pagina</a>-->\n");
      out.write("        <a href=\"CerrarSesion\" class=\"sesion\"><i class=\"fa-solid fa-power-off\" style=\"font-size: 6vh; padding: 2vh 0;\"></i>Cerrar Sesión</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"contenedor\">\n");
      out.write("        <div class=\"titulo\">Menú Principal</div>\n");
      out.write("        <div class=\"caja\">\n");
      out.write("            <div class=\"opciones\">\n");
      out.write("                <div class=\"imagen\">\n");
      out.write("                    <img src=\"https://cdn.icon-icons.com/icons2/3560/PNG/512/customer_man_avatar_person_people_thinking_about_shopping_shopping_ideas_icon_225182.png\" alt=\"\" style=\"width: 100%; height: 100%;\">\n");
      out.write("                </div>\n");
      out.write("                <a href=\"MenuCliente.jsp\">Cliente</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"opciones\">\n");
      out.write("                <div class=\"imagen\">\n");
      out.write("                    <img src=\"https://cdn-icons-png.flaticon.com/512/3240/3240782.png\" alt=\"\" style=\"width: 100%; height: 100%;\">\n");
      out.write("                </div>\n");
      out.write("                <a href=\"\">Producto</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"opciones\">\n");
      out.write("                <div class=\"imagen\">\n");
      out.write("                    <img src=\"https://cdn-icons-png.flaticon.com/512/6384/6384868.png\" alt=\"\" style=\"width: 100%; height: 100%;\">\n");
      out.write("                </div>\n");
      out.write("                <a href=\"\">Pedidos</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
