/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-01 18:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import Entidades.Pedido;
import Entidades.DetallePedido;

public final class MenuPedidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/maria/Documents/GitHub/SistemasDistribuidos_PaginaWebFinal/SistemasDistribuidos_PaginaWebFinal/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719637880568L));
    _jspx_dependants.put("/ModalSesionExpirada.jsp", Long.valueOf(1719637880547L));
    _jspx_dependants.put("/NavBar.jsp", Long.valueOf(1719797279876L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Entidades.Pedido");
    _jspx_imports_classes.add("Entidades.DetallePedido");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Listado de Pedidos</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/26a3cc7edf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-backdrop {\r\n");
      out.write("            background-color: rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 0.5rem;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .btnDesplegable {\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            width: 6%;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            transition: transform 0.5s ease;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas {\r\n");
      out.write("            height: 12vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:hover {\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:nth-child(n+2) {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:last-child {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            margin-bottom: 2vh;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas i {\r\n");
      out.write("            font-size: 5vh;\r\n");
      out.write("            padding: 0.2vh;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas h1 {\r\n");
      out.write("            font-size: 2.5vh;\r\n");
      out.write("            padding: 0.2vh;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .navMasContenido {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navegador {\r\n");
      out.write("            height: 12vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("        .imagen {\r\n");
      out.write("            width: 12wh;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .imagen img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .datos {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .Aparecer {\r\n");
      out.write("            transform: translateX(0);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"display: flex\">\r\n");
      out.write("    ");

    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    if (session.getAttribute("user") == null) {
        response.sendRedirect("Login.jsp");
    }

    String XD = (String) request.getAttribute("Nombre");
    String idUsuario = (String) request.getAttribute("Id_Usuario");

    System.out.println("El nombre en jsp es: " + XD);
    System.out.println("El ID USUARIOS ES===================================" + idUsuario);

    // Verificar si el usuario es administrador

   //CAMBIOOO
boolean esAdmin = idUsuario != null && (idUsuario.startsWith("A") || idUsuario.startsWith("a"));
    //FIN CAMBIO

    System.out.println("el admin es: " + esAdmin);

    // Determinar la pÃÂ¡gina activa
    String currentPage = request.getRequestURI();
    boolean isDashboard = currentPage.contains("Dashboard.jsp");
    boolean isClientes = currentPage.contains("MenuClientes.jsp");
    boolean isProductos = currentPage.contains("MenuProductos.jsp");
    boolean isPedidos = currentPage.contains("MenuPedidos.jsp");
    boolean isVentas = currentPage.contains("MenuVentas.jsp");
    boolean isDemandas = currentPage.contains("MenuDemandas.jsp");
    boolean isUsuarios = currentPage.contains("MenuUsuarios.jsp");


      out.write("\r\n");
      out.write("<body style=\"display: flex\"> \r\n");
      out.write("    <div id=\"sidebar1\" class=\"btnDesplegable\" style=\"background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerDashboard?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isDashboard ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-gauge\"></i>\r\n");
      out.write("            <h1>Dashboard</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("            <h1>Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1>Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1>Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1>Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerDemanda?Op=VerPagina&id=");
      out.print( idUsuario);
      out.write("&nom=");
      out.print( XD);
      out.write("\" style=\"text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fas fa-chart-bar\"></i>\r\n");
      out.write("            <h1>Demanda Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1>Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 }
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1>Cerrar Sesion</h1>\r\n");
      out.write("        </a>            \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"sidebar2\" class=\"btnDesplegable\" style=\"transform: translateX(-100%); width: 12%; background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerDashboard?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isDashboard ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-gauge\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Dashboard</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerDemanda?Op=VerPagina&id=");
      out.print( idUsuario);
      out.write("&nom=");
      out.print( XD);
      out.write("\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-chart-bar\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Demanda Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 }
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"flex-direction: row; text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3vh;\">Cerrar Sesion</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navMasContenido\">\r\n");
      out.write("        <nav class=\"navegador\" style=\"padding-left: 6%; background-color: #ffd700;\">\r\n");
      out.write("            <div class=\"imagen\">\r\n");
      out.write("                <img src=\"https://www.logogenio.es/icons/preview/11175\" alt=\"Logo\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"datos\">\r\n");
      out.write("                <h2>Bienvenido </h2>\r\n");
      out.write("                <h1>");
      out.print( XD);
      out.write("</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function toggleSidebar() {/*Para el menu*/\r\n");
      out.write("                const sidebar1 = document.getElementById('sidebar1');\r\n");
      out.write("                const sidebar2 = document.getElementById('sidebar2');\r\n");
      out.write("                if (sidebar1.style.transform === 'translateX(-100%)') {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(0)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(-100%)';\r\n");
      out.write("                } else {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(-100%)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(0)';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </script>    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"navMasContenido\">\r\n");
      out.write("        <div class=\"Contenido\" style=\"padding-left: 6%; background-color: #87ceeb; display: flex; justify-content: center; width: 100%;\">\r\n");
      out.write("            <div class=\"tabla\" style=\"width: 70%\">\r\n");
      out.write("                <div class=\"titulo\" style=\"font-size: 10vh; text-align: center\">LISTA PEDIDOS</div>\r\n");
      out.write("                <form action=\"ControlerPedido\" method=\"post\" style=\"display:inline\">\r\n");
      out.write("                    <button type=\"submit\" name=\"Op\" value=\"Exportar\" class=\"btn btn-primary\" style=\"margin: 1vh\">\r\n");
      out.write("                        <i class=\"fa-solid fa-file-export\" style=\"padding: 0px 0.5vh\"></i> Exportar\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <table class=\"table table-striped\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"col\">Id_Pedido</th>\r\n");
      out.write("                            <th scope=\"col\">Cliente</th>\r\n");
      out.write("                            <th scope=\"col\">Usuario</th>\r\n");
      out.write("                            <th scope=\"col\">Fecha</th>\r\n");
      out.write("                            <th scope=\"col\">SubTotal</th>\r\n");
      out.write("                            <th scope=\"col\">TotalVenta</th>\r\n");
      out.write("                            <th scope=\"col\">Detalles</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <p>Tu sesión expirará en <span id=\"countdown\"></span> segundos.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("        background-color: rgb(0,0,0);\r\n");
      out.write("        background-color: rgba(0,0,0,0.4);\r\n");
      out.write("        padding-top: 60px;\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 5% auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span{\r\n");
      out.write("        font-size: 3.5vh;\r\n");
      out.write("        margin: 0.5vh;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var totalInactiveTime = 100000; // 10 segundos\r\n");
      out.write("    var warningTime = 5; // 5 segundos antes del logout\r\n");
      out.write("    var time, warningTimer;\r\n");
      out.write("\r\n");
      out.write("    window.onload = function () {\r\n");
      out.write("        resetTimer();\r\n");
      out.write("        document.addEventListener('mousemove', resetTimer, false);\r\n");
      out.write("        document.addEventListener('keypress', resetTimer, false);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function startLogoutWarning() {\r\n");
      out.write("        var countdown = warningTime;\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        var countdownElement = document.getElementById(\"countdown\");\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("        countdownElement.innerText = countdown;\r\n");
      out.write("\r\n");
      out.write("        warningTimer = setInterval(function () {\r\n");
      out.write("            countdown--;\r\n");
      out.write("            countdownElement.innerText = countdown;\r\n");
      out.write("            if (countdown < 0) {\r\n");
      out.write("                clearInterval(warningTimer);\r\n");
      out.write("                logout();\r\n");
      out.write("            }\r\n");
      out.write("        }, 1000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function logout() {\r\n");
      out.write("        alert(\"Tu sesión ha expirado.\");\r\n");
      out.write("        window.location.href = 'CerrarSesion'; /*Es el controlador que hice para que se cierre */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function resetTimer() {\r\n");
      out.write("        clearTimeout(time);\r\n");
      out.write("        clearInterval(warningTimer); // Detener el contador de advertencia si está en curso\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        modal.style.display = \"none\"; // Ocultar el modal si se muestra\r\n");
      out.write("        time = setTimeout(startLogoutWarning, (totalInactiveTime - warningTime) * 1000);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleSidebar() {/*Para el menu*/\r\n");
      out.write("                const sidebar1 = document.getElementById('sidebar1');\r\n");
      out.write("                const sidebar2 = document.getElementById('sidebar2');\r\n");
      out.write("                if (sidebar1.style.transform === 'translateX(-100%)') {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(0)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(-100%)';\r\n");
      out.write("                } else {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(-100%)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(0)';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /MenuPedidos.jsp(111,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pedido");
      // /MenuPedidos.jsp(111,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/MenuPedidos.jsp(111,28) '${pedidos}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pedidos}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <tr>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idCliente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idUsuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.fecha}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.subTotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.totalVenta}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>\r\n");
            out.write("                                        <button type=\"button\" class=\"btn btn-info\" data-bs-toggle=\"modal\" data-bs-target=\"#modalDetalles");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                            Ver Detalles\r\n");
            out.write("                                        </button>\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /MenuPedidos.jsp(131,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("pedido");
      // /MenuPedidos.jsp(131,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/MenuPedidos.jsp(131,16) '${pedidos}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pedidos}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <div class=\"modal fade\" id=\"modalDetalles");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modalDetalles");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Label\" aria-hidden=\"true\" style=\"z-index: 99999999\">\r\n");
            out.write("                        <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
            out.write("                            <div class=\"modal-content\">\r\n");
            out.write("                                <div class=\"modal-header\">\r\n");
            out.write("                                    <h5 class=\"modal-title\" id=\"modalDetalles");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("Label\">Detalles del Pedido ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <div class=\"modal-body\">\r\n");
            out.write("                                    <table class=\"table table-striped\">\r\n");
            out.write("                                        <thead>\r\n");
            out.write("                                            <tr>\r\n");
            out.write("                                                <th scope=\"col\">Id_DetallePedido</th>\r\n");
            out.write("                                                <th scope=\"col\">Id_Pedido</th>\r\n");
            out.write("                                                <th scope=\"col\">Productos</th>\r\n");
            out.write("                                                <th scope=\"col\">Cantidad</th>\r\n");
            out.write("                                                <th scope=\"col\">Precio</th>\r\n");
            out.write("                                                <th scope=\"col\">TotalDeta</th>\r\n");
            out.write("                                            </tr>\r\n");
            out.write("                                            </thead>\r\n");
            out.write("                                            <tbody>\r\n");
            out.write("                                                ");
            if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                        </tbody>\r\n");
            out.write("                                    </table>\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <div class=\"modal-footer\">\r\n");
            out.write("                                    <form action=\"ControlerPedido\" method=\"post\" style=\"display:inline\">\r\n");
            out.write("                                        <input type=\"hidden\" name=\"Id_Pedido\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pedido.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        <button type=\"submit\" name=\"Op\" value=\"ExportarDetalles\" class=\"btn btn-primary\">\r\n");
            out.write("                                            <i class=\"fa-solid fa-file-export\" style=\"padding: 0px 0.5vh\"></i> Exportar\r\n");
            out.write("                                        </button>\r\n");
            out.write("                                    </form>\r\n");
            out.write("                                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /MenuPedidos.jsp(152,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("detalle");
      // /MenuPedidos.jsp(152,48) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/MenuPedidos.jsp(152,48) '${detalles}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${detalles}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                                    ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("                                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /MenuPedidos.jsp(153,52) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.idPedido eq pedido.idPedido}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                        <tr>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.idDetallePedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.descripcion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.cantidad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.precio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detalle.totalDeta}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                                                        </tr>\r\n");
          out.write("                                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
