/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-23 02:15:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MenuVentas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717378218116L));
    _jspx_dependants.put("/ModalSesionExpirada.jsp", Long.valueOf(1717456573208L));
    _jspx_dependants.put("jar:file:/D:/maria/Descargas/SistemasDistribuidos_PaginaWebFinal/SistemasDistribuidos_PaginaWebFinal/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/NavBar.jsp", Long.valueOf(1719108836955L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Ventas</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/26a3cc7edf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        body, html {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .btnDesplegable {\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            width: 6%;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            transition: transform 0.5s ease;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas {\r\n");
      out.write("            height: 12vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:hover {\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:nth-child(n+2) {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas:last-child {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            margin-bottom: 2vh;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas i {\r\n");
      out.write("            font-size: 5vh;\r\n");
      out.write("            padding: 0.2vh;\r\n");
      out.write("        }\r\n");
      out.write("        .cajas h1 {\r\n");
      out.write("            font-size: 2.5vh;\r\n");
      out.write("            padding: 0.2vh;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .navMasContenido {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navegador {\r\n");
      out.write("            height: 12vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("        .imagen {\r\n");
      out.write("            width: 12wh;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .imagen img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .datos {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .Contenido {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .tabla {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            margin: 20px 0; \r\n");
      out.write("        }\r\n");
      out.write("        .titulo {\r\n");
      out.write("            font-size: 10vh;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px; \r\n");
      out.write("        }\r\n");
      out.write("        .content-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .card-footer {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .table td{\r\n");
      out.write("            padding: 15px; \r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("     ");
String idUsuario4 = (String) request.getAttribute("Id_Usuario");
     System.out.println("Usuario traido hacia jsp"+idUsuario4);
      out.write("\r\n");
      out.write("    ");

    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    if (session.getAttribute("user") == null) {
        response.sendRedirect("Login.jsp");
    }

    String XD = (String) request.getAttribute("Nombre");
    String idUsuario = (String) request.getAttribute("Id_Usuario");

    System.out.println("El nombre en jsp es: " + XD);
    System.out.println("El ID USUARIOS ES==================================="+idUsuario);

    // Verificar si el usuario es administrador
    boolean esAdmin = idUsuario != null && idUsuario.startsWith("A") || idUsuario.startsWith("a");
    System.out.println("el admin es: "+ esAdmin);

    // Determinar la pÃÂ¡gina activa
    String currentPage = request.getRequestURI();
    boolean isClientes = currentPage.contains("MenuClientes.jsp");
    boolean isProductos = currentPage.contains("MenuProductos.jsp");
    boolean isPedidos = currentPage.contains("MenuPedidos.jsp");
    boolean isVentas = currentPage.contains("MenuVentas.jsp");
    boolean isUsuarios = currentPage.contains("MenuUsuarios.jsp");
    

      out.write("\r\n");
      out.write("<body style=\"display: flex\"> \r\n");
      out.write("    <div id=\"sidebar1\" class=\"btnDesplegable\" style=\"background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1>Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1>Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1>Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1>Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1>Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1>Cerrar Sesion</h1>\r\n");
      out.write("        </a>            \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"sidebar2\" class=\"btnDesplegable\" style=\"transform: translateX(-100%); width: 12%; background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"flex-direction: row; text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3vh;\">Cerrar Sesion</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navMasContenido\">\r\n");
      out.write("        <nav class=\"navegador\" style=\"padding-left: 6%; background-color: #ffd700;\">\r\n");
      out.write("            <div class=\"imagen\">\r\n");
      out.write("                <img src=\"https://www.logogenio.es/icons/preview/11175\" alt=\"Logo\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"datos\">\r\n");
      out.write("                <h2>Bienvenido </h2>\r\n");
      out.write("                <h1>");
      out.print( XD );
      out.write("</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"navMasContenido\">\r\n");
      out.write("        <div class=\"Contenido\">\r\n");
      out.write("            <div class=\"tabla\">\r\n");
      out.write("                <div class=\"titulo\">Ventas</div>\r\n");
      out.write("                <div class=\"content-container\">\r\n");
      out.write("                    <div class=\"col-sm-4\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Datos del Cliente</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <form action=\"ControlerVenta\" method=\"post\"> \r\n");
      out.write("                                    <input type=\"hidden\" name=\"Op\" value=\"BuscarCliente\"> \r\n");
      out.write("                                    <div class=\"form-group row\" style=\"margin:5px\">\r\n");
      out.write("                                         <div class=\"col-sm-8\" style=\"margin-top:10px;\">\r\n");
      out.write("                                            <input type=\"text\" name=\"dni\" class=\"form-control\" placeholder=\"DNI del Cliente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.dniCliente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-sm-4\">\r\n");
      out.write("                                            <input type=\"submit\" name=\"accion\" value=\"Buscar\" class=\"btn btn-outline-info btn-block\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <input type=\"text\" name=\"nombre\" class=\"form-control\" placeholder=\"Nombre del Cliente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.nombreCliente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-sm-8\" style=\"margin-top:10px;\">\r\n");
      out.write("                                            <input type=\"text\" name=\"apellidos\" class=\"form-control\" placeholder=\"Apellidos del Cliente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.apellidosCliente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                       <div class=\"col-sm-4\" style=\"margin-top:10px;\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-outline-secondary btn-block\" onclick=\"limpiarCliente()\" style=\"font-size: 95%;\">Limpiar</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                       \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                        <!-- Modal Cliente no Registrado-->\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Buscar Producto</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <form action=\"ControlerVenta\" method=\"post\" id=\"formBuscarProducto\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"Op\" value=\"BuscarProducto\"> \r\n");
      out.write("                                    <div class=\"form-group row\" style=\"margin:5px\">\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <input type=\"text\" id=\"nombreProductoInput\" name=\"nombreProducto\" class=\"form-control\" placeholder=\"Nombre del Producto\" autocomplete=\"off\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombreProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <select id=\"nombreProductoSelect\" name=\"nombreProductoSelect\" class=\"form-control\" style=\"display: none;\">\r\n");
      out.write("                                                <!-- Las opciones serán añadidas dinámicamente por JavaScript -->\r\n");
      out.write("                                            </select>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-sm-4\">\r\n");
      out.write("                                            <input type=\"submit\" name=\"accion\" value=\"Buscar\" class=\"btn btn-outline-info btn-block\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("\r\n");
      out.write("                                <!-- Modal Producto no Registrado-->\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-7\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"d-flex col-sm-5 ml-auto\">\r\n");
      out.write("                                    <label>Nro.Serie Anterior: </label>\r\n");
      out.write("                                    <input type=\"text\" name=\"\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.idPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <table id=\"cuerpoTabla\" class=\"table table-hover\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Nro</th>\r\n");
      out.write("                                            <th>Codigo</th>\r\n");
      out.write("                                            <th>Nombre</th>\r\n");
      out.write("                                            <th>Precio</th>\r\n");
      out.write("                                            <th>Cantidad</th>\r\n");
      out.write("                                            <th>Importe</th>\r\n");
      out.write("                                            <th>Acciones</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6 ml-auto\">\r\n");
      out.write("                                <div class=\"form-group d-flex\">\r\n");
      out.write("                                    <label class=\"mr-4\">SubTotal: </label>\r\n");
      out.write("                                    <input type=\"text\" name=\"subtotalCompra\" id=\"subtotalCompra\" class=\"form-control form-control-sm\" style=\"width: 100px;\" value=\"S/. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group d-flex\">\r\n");
      out.write("                                    <label class=\"mr-4\">IGV 18%:</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"IGV\" id=\"IGV\" class=\"form-control form-control-sm\" style=\"width: 100px;\" value=\"S/. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${igv}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex\">\r\n");
      out.write("                                <form action=\"ControlerVenta\" method=\"post\" onsubmit=\"return validarFormulario()\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"Op\" value=\"GenerarVenta\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"Generar Venta\" class=\"btn btn-success\">\r\n");
      out.write("                                </form>\r\n");
      out.write("\r\n");
      out.write("                                <form action=\"ControlerVenta\" method=\"post\" style=\"margin-left: 10px;\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"Op\" value=\"CancelarVenta\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"Cancelar\" class=\"btn btn-danger\">\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div class=\"col-sm-3 ml-auto\">\r\n");
      out.write("                                    <input type=\"text\" name=\"totalCompra\" id=\"totalCompra\" class=\"form-control\" value=\"S/. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCompra}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("0\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"ventaGuardadaModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"cerrarModal('ventaGuardadaModal')\">&times;</span>\r\n");
      out.write("        <p>Venta generada correctamente.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <!-- Modal Campos Vacíos-->\r\n");
      out.write("        <div class=\"modal\" id=\"camposVaciosModal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"cerrarModal('camposVaciosModal')\">&times;</span>\r\n");
      out.write("        <p>Por favor, complete todos los campos antes de registrar la venta.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- Modal Sin Productos -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        \r\n");
      out.write("        function actualizarStock() {\r\n");
      out.write("            const cantidadElement = document.getElementById('cant');\r\n");
      out.write("            const stockElement = document.getElementById('stock');\r\n");
      out.write("            const stockOriginal = parseInt(stockElement.defaultValue);\r\n");
      out.write("            const cantidad = parseInt(cantidadElement.value);\r\n");
      out.write("\r\n");
      out.write("            if (!isNaN(stockOriginal) && !isNaN(cantidad)) {\r\n");
      out.write("                const nuevoStock = stockOriginal - cantidad;\r\n");
      out.write("                stockElement.value = nuevoStock < 0 ? 0 : nuevoStock;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Validar que la cantidad no exceda el stock disponible\r\n");
      out.write("        function validarCantidadProducto() {\r\n");
      out.write("            const cantidadElement = document.getElementById('cant');\r\n");
      out.write("            const stockElement = document.getElementById('stock');\r\n");
      out.write("            const cantidad = parseInt(cantidadElement.value);\r\n");
      out.write("            const stock = parseInt(stockElement.value);\r\n");
      out.write("\r\n");
      out.write("            if (cantidad > stock) {\r\n");
      out.write("                alert('La cantidad no puede exceder el stock disponible.');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("                $('#nombreProductoInput').on('input', function() {\r\n");
      out.write("                    var term = $(this).val();\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                        type: 'GET',\r\n");
      out.write("                        url: 'ControlerVenta?Op=BuscarProductosAutocompletado&term=' + term,\r\n");
      out.write("                        dataType: 'json',\r\n");
      out.write("                        success: function(data) {\r\n");
      out.write("                            $('#nombreProductoSelect').empty();\r\n");
      out.write("                            if (data.length > 0) {\r\n");
      out.write("                               \r\n");
      out.write("                                $('#nombreProductoSelect').show();\r\n");
      out.write("                                \r\n");
      out.write("                                $('#nombreProductoSelect').append('<option value=\"\">Selecciona un producto...</option>');\r\n");
      out.write("                                $.each(data, function(index, value) {\r\n");
      out.write("                                    $('#nombreProductoSelect').append('<option value=\"' + value + '\">' + value + '</option>');\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                \r\n");
      out.write("                                $('#nombreProductoSelect').hide();\r\n");
      out.write("                                $('#nombreProductoSelect').append('<option value=\"\">No se encontraron productos</option>');\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                $('#nombreProductoSelect').on('change', function() {\r\n");
      out.write("                    var selectedOption = $(this).val();\r\n");
      out.write("                    $('#nombreProductoInput').val(selectedOption);\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#nombreProductoSelect').on('change', function() {\r\n");
      out.write("                    var selectedOption = $(this).val();\r\n");
      out.write("                    // Función para eliminar tildes\r\n");
      out.write("                    var textoSinTildes = eliminarTildes(selectedOption);\r\n");
      out.write("                    $('#nombreProductoInput').val(textoSinTildes);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // elimina tildes de un texto\r\n");
      out.write("                function eliminarTildes(texto) {\r\n");
      out.write("                    return texto.normalize(\"NFD\").replace(/[\\u0300-\\u036f]/g, \"\");\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            // Mostrar modal de cliente no registrado si está presente\r\n");
      out.write("            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeClienteNoRegistrado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") {\r\n");
      out.write("                document.getElementById(\"clienteNoRegistradoModal\").style.display = 'block';\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    document.getElementById(\"clienteNoRegistradoModal\").style.display = 'none';\r\n");
      out.write("                }, 5000);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            \r\n");
      out.write("            // Mostrar modal de productos no encontrados\r\n");
      out.write("            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeProductoNoRegistrado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") {\r\n");
      out.write("                document.getElementById(\"ProductoNoRegistradoModal\").style.display = 'block';\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    document.getElementById(\"ProductoNoRegistradoModal\").style.display = 'none';\r\n");
      out.write("                }, 5000);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            \r\n");
      out.write("            // Mostrar modal sin productos\r\n");
      out.write("            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeSinProductos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") {\r\n");
      out.write("                document.getElementById(\"productosVaciosModal\").style.display = 'block';\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    document.getElementById(\"productosVaciosModal\").style.display = 'none';\r\n");
      out.write("                }, 5000);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            document.getElementById(\"camposVaciosModal\");\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                 document.getElementById(\"camposVaciosModal\").style.display = 'none';\r\n");
      out.write("            }, 5000); // 5000 milisegundos = 5 segundos\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        function cerrarModal(idModal) {\r\n");
      out.write("            var modal = document.getElementById(idModal);\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function validarFormulario() {\r\n");
      out.write("            if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.listaVentas == null || sessionScope.listaVentas.isEmpty()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("                document.getElementById(\"productosVaciosModal\").style.display = 'block';\r\n");
      out.write("                return false; // Evitar el envío del formulario\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("          const modal = document.getElementById(\"ventaGuardadaModal\");\r\n");
      out.write("          const span = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("          // Mostrar el modal \r\n");
      out.write("          if (window.location.search.includes(\"ventaGuardada=true\")) {\r\n");
      out.write("            modal.style.display = \"block\";\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                modal.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("                window.location.href = \"MenuVentas.jsp\";\r\n");
      out.write("            }, 5000); \r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        // Cerrar el modal con la X\r\n");
      out.write("        span.onclick = function() {\r\n");
      out.write("          modal.style.display = \"none\";\r\n");
      out.write("          window.location.href = \"MenuVentas.jsp\"; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Cerrar el modal con clic fuera del modal\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("          if (event.target == modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("            window.location.href = \"MenuVentas.jsp\"; \r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function validarCantidadProducto() {\r\n");
      out.write("    var cantidad = parseInt(document.getElementsByName('cantidadProducto')[0].value);\r\n");
      out.write("    var stock = parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stockProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\r\n");
      out.write("    if (cantidad > stock) {\r\n");
      out.write("        alert(\"La cantidad que desea comprar es mayor al stock disponible (\" + stock + \")\");\r\n");
      out.write("        return false; // Evitar que se envíe el formulario\r\n");
      out.write("    }\r\n");
      out.write("    return true; // Permitir el envío del formulario si todo está correcto\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function validarFormulario() {\r\n");
      out.write("        // Verificar si los campos obligatorios están vacíos\r\n");
      out.write("        var dni = document.getElementsByName('dni')[0].value;\r\n");
      out.write("        var nombre = document.getElementsByName('nombre')[0].value;\r\n");
      out.write("        var apellidos = document.getElementsByName('apellidos')[0].value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if (dni === '' || nombre === '' || apellidos === '' ) {\r\n");
      out.write("            // Mostrar el modal de campos vacíos\r\n");
      out.write("            document.getElementById('camposVaciosModal').style.display = 'block';\r\n");
      out.write("            return false; // Evitar que se envíe el formulario\r\n");
      out.write("        }\r\n");
      out.write("        return true; // Permitir el envío del formulario si todo está completo \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function cerrarModal(idModal) {\r\n");
      out.write("        var modal = document.getElementById(idModal);\r\n");
      out.write("        modal.style.display = \"none\";\r\n");
      out.write("        window.location.href = \"MenuVentas.jsp\"; // Redireccionar a menu ventas\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("      function limpiarCliente() {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'ControlerVenta',\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            data: {\r\n");
      out.write("                Op: 'LimpiarCliente'\r\n");
      out.write("            },\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                \r\n");
      out.write("                document.getElementsByName('dni')[0].value = '';\r\n");
      out.write("                document.getElementsByName('nombre')[0].value = '';\r\n");
      out.write("                document.getElementsByName('apellidos')[0].value = '';\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("        function toggleSidebar() {/*Para el menu*/\r\n");
      out.write("                const sidebar1 = document.getElementById('sidebar1');\r\n");
      out.write("                const sidebar2 = document.getElementById('sidebar2');\r\n");
      out.write("                if (sidebar1.style.transform === 'translateX(-100%)') {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(0)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(-100%)';\r\n");
      out.write("                } else {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(-100%)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(0)';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS Modal Venta Generada -->\r\n");
      out.write("<style>\r\n");
      out.write(".modal {\r\n");
      out.write("  display: none; \r\n");
      out.write("  position: fixed; \r\n");
      out.write("  z-index: 1; \r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 100%; \r\n");
      out.write("  height: 100%; \r\n");
      out.write("  overflow: auto; \r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.5); /* Fondo transparente negro */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("  background-color: #fefefe;\r\n");
      out.write("  margin: 15% auto; /* Centrado verticalmente */\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  border: 1px solid #888;\r\n");
      out.write("  width: 50%; \r\n");
      out.write("  height: 10%;\r\n");
      out.write("  position: relative; /* Para posicionar el X */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close {\r\n");
      out.write("  color: #aaa;\r\n");
      out.write("  position: absolute; \r\n");
      out.write("  top: 10px;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover,\r\n");
      out.write(".close:focus {\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" /* css para modal */\r\n");
      out.write("    .modal_cli {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("        background-color: rgb(0,0,0);\r\n");
      out.write("        background-color: rgba(0,0,0,0.4);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .modal_cli-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 15% auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .close_cli {\r\n");
      out.write("        color: #aaaaaa;\r\n");
      out.write("        float: right;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .close_cli:hover,\r\n");
      out.write("    .close_cli:focus {\r\n");
      out.write("        color: #000;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("                \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <p>Tu sesión expirará en <span id=\"countdown\"></span> segundos.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("        background-color: rgb(0,0,0);\r\n");
      out.write("        background-color: rgba(0,0,0,0.4);\r\n");
      out.write("        padding-top: 60px;\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 5% auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span{\r\n");
      out.write("        font-size: 3.5vh;\r\n");
      out.write("        margin: 0.5vh;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var totalInactiveTime = 100000; // 10 segundos\r\n");
      out.write("    var warningTime = 5; // 5 segundos antes del logout\r\n");
      out.write("    var time, warningTimer;\r\n");
      out.write("\r\n");
      out.write("    window.onload = function () {\r\n");
      out.write("        resetTimer();\r\n");
      out.write("        document.addEventListener('mousemove', resetTimer, false);\r\n");
      out.write("        document.addEventListener('keypress', resetTimer, false);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function startLogoutWarning() {\r\n");
      out.write("        var countdown = warningTime;\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        var countdownElement = document.getElementById(\"countdown\");\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("        countdownElement.innerText = countdown;\r\n");
      out.write("\r\n");
      out.write("        warningTimer = setInterval(function () {\r\n");
      out.write("            countdown--;\r\n");
      out.write("            countdownElement.innerText = countdown;\r\n");
      out.write("            if (countdown < 0) {\r\n");
      out.write("                clearInterval(warningTimer);\r\n");
      out.write("                logout();\r\n");
      out.write("            }\r\n");
      out.write("        }, 1000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function logout() {\r\n");
      out.write("        alert(\"Tu sesión ha expirado.\");\r\n");
      out.write("        window.location.href = 'CerrarSesion'; /*Es el controlador que hice para que se cierre */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function resetTimer() {\r\n");
      out.write("        clearTimeout(time);\r\n");
      out.write("        clearInterval(warningTimer); // Detener el contador de advertencia si está en curso\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        modal.style.display = \"none\"; // Ocultar el modal si se muestra\r\n");
      out.write("        time = setTimeout(startLogoutWarning, (totalInactiveTime - warningTime) * 1000);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /MenuVentas.jsp(153,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeClienteNoRegistrado}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        <div class=\"modal_cli\" id=\"clienteNoRegistradoModal\" style=\"display: block;\">\r\n");
          out.write("                                            <div class=\"modal-content\">\r\n");
          out.write("                                                <span class=\"close\">&times;</span>\r\n");
          out.write("                                                <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.mensajeClienteNoRegistrado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /MenuVentas.jsp(186,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeProductoNoRegistrado}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        <div class=\"modal_cli\" id=\"ProductoNoRegistradoModal\" style=\"display: block;\">\r\n");
          out.write("                                            <div class=\"modal-content\">\r\n");
          out.write("                                                <span class=\"close\">&times;</span>\r\n");
          out.write("                                                <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.mensajeProductoNoRegistrado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /MenuVentas.jsp(196,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty nombreProducto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <div class=\"form-group\">\r\n");
          out.write("                                        <label>Datos del Producto</label>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <form action=\"ControlerVenta\" method=\"post\" onsubmit=\"return validarCantidadProducto()\">\r\n");
          out.write("                                        <input type=\"hidden\" name=\"Op\" value=\"AgregarProducto\">\r\n");
          out.write("                                        <input type=\"hidden\" name=\"codigoProducto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${codigoProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        <input type=\"hidden\" name=\"nombreProducto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombreProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        <input type=\"hidden\" name=\"precioProducto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${precioProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        <input type=\"hidden\" name=\"stockProducto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stockProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        <div class=\"form-group row\" style=\"margin:5px\">\r\n");
          out.write("                                            <div class=\"col-sm-8\">\r\n");
          out.write("                                                <input type=\"text\" id=\"codigo\" name=\"codigoProducto\" class=\"form-control\" placeholder=\"Código del Producto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${codigoProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                            <div class=\"col-sm-8\">\r\n");
          out.write("                                                <input type=\"text\" id=\"precio\" name=\"precioProducto\" class=\"form-control\" placeholder=\"Precio del Producto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${precioProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                            <div class=\"col-sm-3\">\r\n");
          out.write("                                                <input type=\"number\" id=\"cant\" value=\"1\" name=\"cantidadProducto\" placeholder=\"\" class=\"form-control\" style=\"width: 80px;\" onchange=\"actualizarStock()\">\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                            <div class=\"col-sm-8\" style=\"margin-top:10px;\">\r\n");
          out.write("                                                <input type=\"text\" id=\"stock\" name=\"stockProducto\" class=\"form-control\" placeholder=\"Stock del Producto\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stockProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly>\r\n");
          out.write("                                            </div>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                        <div class=\"form-group\">\r\n");
          out.write("                                            <button type=\"submit\" class=\"btn btn-outline-primary\">Agregar Producto</button>\r\n");
          out.write("                                        </div>\r\n");
          out.write("                                    </form>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /MenuVentas.jsp(250,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("venta");
      // /MenuVentas.jsp(250,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/MenuVentas.jsp(250,40) '${sessionScope.listaVentas}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.listaVentas}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <tr>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.codigoProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.nombreProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.precioProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.cantidadProducto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.totalDeta}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                               <td>\r\n");
            out.write("                                                    <!-- Enlaces para editar y eliminar productos -->\r\n");
            out.write("                                                    <a href=\"ControlerVenta?Op=EditarProducto&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-info btn-sm\">Editar</a>\r\n");
            out.write("                                                    <a href=\"ControlerVenta?Op=EliminarProducto&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${venta.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-danger btn-sm\">Eliminar</a>\r\n");
            out.write("                                                </td>\r\n");
            out.write("                                            </tr>\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /MenuVentas.jsp(318,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.mensajeSinProductos}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <div id=\"productosVaciosModal\" class=\"modal\" style=\"display: block;\">\r\n");
          out.write("            <div class=\"modal-content\">\r\n");
          out.write("                <span class=\"close\" onclick=\"cerrarModal('productosVaciosModal')\">&times;</span>\r\n");
          out.write("                <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.mensajeSinProductos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("            </div>\r\n");
          out.write("        </div>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
