/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-23 02:13:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import Entidades.Cliente;

public final class MenuUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717378218116L));
    _jspx_dependants.put("/ModalSesionExpirada.jsp", Long.valueOf(1717456573208L));
    _jspx_dependants.put("jar:file:/D:/maria/Descargas/SistemasDistribuidos_PaginaWebFinal/SistemasDistribuidos_PaginaWebFinal/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/NavBar.jsp", Long.valueOf(1719108836955L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Entidades.Cliente");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Cliente> Lista = (List<Cliente>) request.getAttribute("Lista");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("        <script src=\"https://kit.fontawesome.com/26a3cc7edf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("        <style>\r\n");
      out.write("            * {\r\n");
      out.write("                margin: 0px;\r\n");
      out.write("                padding: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .btnDesplegable {\r\n");
      out.write("                height: 100vh;\r\n");
      out.write("                width: 6%;\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                transition: transform 0.5s ease;\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas {\r\n");
      out.write("                height: 12vh;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas:hover{\r\n");
      out.write("                background-color: #87ceeb;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas:nth-child(n+2) {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas:last-child {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                bottom: 0;\r\n");
      out.write("                margin-bottom: 2vh;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas i {\r\n");
      out.write("                font-size: 5vh;\r\n");
      out.write("                padding: 0.2vh;\r\n");
      out.write("            }\r\n");
      out.write("            .cajas h1 {\r\n");
      out.write("                font-size: 2.5vh;\r\n");
      out.write("                padding: 0.2vh;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .navMasContenido {\r\n");
      out.write("                /*width: 94vw;*/\r\n");
      out.write("                width: 100%;\r\n");
      out.write("\r\n");
      out.write("                /*margin-left: 6%;*/\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            .navegador {\r\n");
      out.write("                height: 12vh;\r\n");
      out.write("\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-around;\r\n");
      out.write("            }\r\n");
      out.write("            .imagen {\r\n");
      out.write("                width: 12wh;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            .imagen img {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            .datos {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .Aparecer {\r\n");
      out.write("                transform: translateX(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body style=\"display: flex\">    \r\n");
      out.write("        ");

    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    if (session.getAttribute("user") == null) {
        response.sendRedirect("Login.jsp");
    }

    String XD = (String) request.getAttribute("Nombre");
    String idUsuario = (String) request.getAttribute("Id_Usuario");

    System.out.println("El nombre en jsp es: " + XD);
    System.out.println("El ID USUARIOS ES==================================="+idUsuario);

    // Verificar si el usuario es administrador
    boolean esAdmin = idUsuario != null && idUsuario.startsWith("A") || idUsuario.startsWith("a");
    System.out.println("el admin es: "+ esAdmin);

    // Determinar la pÃÂ¡gina activa
    String currentPage = request.getRequestURI();
    boolean isClientes = currentPage.contains("MenuClientes.jsp");
    boolean isProductos = currentPage.contains("MenuProductos.jsp");
    boolean isPedidos = currentPage.contains("MenuPedidos.jsp");
    boolean isVentas = currentPage.contains("MenuVentas.jsp");
    boolean isUsuarios = currentPage.contains("MenuUsuarios.jsp");
    

      out.write("\r\n");
      out.write("<body style=\"display: flex\"> \r\n");
      out.write("    <div id=\"sidebar1\" class=\"btnDesplegable\" style=\"background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1>Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1>Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1>Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1>Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1>Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1>Cerrar Sesion</h1>\r\n");
      out.write("        </a>            \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"sidebar2\" class=\"btnDesplegable\" style=\"transform: translateX(-100%); width: 12%; background-color: #f0f0f0\">\r\n");
      out.write("        <div class=\"cajas\" onclick=\"toggleSidebar()\" style=\"cursor: pointer;\">\r\n");
      out.write("            <i class=\"fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerCliente?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isClientes ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Clientes</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerProducto?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isProductos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-bottle-water\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Productos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerPedido?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isPedidos ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Pedidos</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerVenta?Op=VerPagina\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isVentas ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-clipboard\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Ventas</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (esAdmin) {
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"ControlerUsuario?Op=Listar\" style=\"flex-direction: row; text-decoration: none; color: black; ");
      out.print( isUsuarios ? "background-color: #87ceeb" : "");
      out.write("\">\r\n");
      out.write("            <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3.5vh;\">Usuarios</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a class=\"cajas\" href=\"CerrarSesion\" style=\"flex-direction: row; text-decoration: none; color: black;\">\r\n");
      out.write("            <i class=\"fa-solid fa-power-off\"></i>\r\n");
      out.write("            <h1 style=\"font-size: 3vh;\">Cerrar Sesion</h1>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navMasContenido\">\r\n");
      out.write("        <nav class=\"navegador\" style=\"padding-left: 6%; background-color: #ffd700;\">\r\n");
      out.write("            <div class=\"imagen\">\r\n");
      out.write("                <img src=\"https://www.logogenio.es/icons/preview/11175\" alt=\"Logo\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"datos\">\r\n");
      out.write("                <h2>Bienvenido </h2>\r\n");
      out.write("                <h1>");
      out.print( XD );
      out.write("</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navMasContenido\">\r\n");
      out.write("            <div class=\"Contenido\" style=\"padding-left: 6%; background-color: #87ceeb; display: flex; justify-content: center; width: 100%;\"><!--Poner TODO ACA-->            \r\n");
      out.write("                <div class=\"tabla\" style=\" width: 90%\">\r\n");
      out.write("                    <div class=\"titulo\" style=\"font-size: 10vh; text-align: center\">LISTA USUARIOS</div>\r\n");
      out.write("                    <a  style=\"margin: 1vh\" href=\"#\" class=\"Agregar btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\" data-id=\"\" data-tipo=\"\" data-raza=\"\" data-nombre=\"\" data-fecha=\"\" data-edad=\"\" data-color=\"\" data-peso=\"\" data-tamano=\"\" data-genero=\"\"><i class=\"fa-solid fa-user-plus\" style=\"padding: 0px 0.5vh\"></i>Agregar</a>\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table table-striped\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("\r\n");
      out.write("                                    <th scope=\"col\">idUsuario</th>\r\n");
      out.write("                                    <th scope=\"col\">Contraseña</th>\r\n");
      out.write("                                    <th scope=\"col\">Apellidos</th>\r\n");
      out.write("                                    <th scope=\"col\">Nombres</th>\r\n");
      out.write("                                    <th scope=\"col\">Imagen</th>\r\n");
      out.write("                                    <th scope=\"col\">Direccion</th>\r\n");
      out.write("                                    <th scope=\"col\">Dni</th>\r\n");
      out.write("                                    <th scope=\"col\">Telefono</th>\r\n");
      out.write("                                    <th scope=\"col\">Movil</th>\r\n");
      out.write("                                    <th scope=\"col\">En Linea</th>\r\n");
      out.write("                                    <th scope=\"col\">Estado</th>\r\n");
      out.write("\r\n");
      out.write("                                    <th scope=\"col\">Editar</th>\r\n");
      out.write("                                    <th scope=\"col\">Eliminar</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal -->\r\n");
      out.write("        <form action=\"ControlerUsuario\" method=\"Post\" class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" style=\"z-index: 1000000\"> <!--enctype=\"multipart/form-data\"-->\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h1 class=\"modal-title fs-5\" id=\"tituloAgregar\">Agregar Clientes</h1>\r\n");
      out.write("                        <h1 class=\"modal-title fs-5\" id=\"tituloEditar\">Actualizar Clientes</h1>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div id=\"updateForm\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"idMascota\" class=\"form-label\">ID Usuario</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"idUsuario\" name=\"cod\" >\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"idMascota\" class=\"form-label\">Contraseña</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"contraseña\" name=\"contra\" >\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"tipoMascota\" class=\"form-label\">Apellidos</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"apellidos\" name=\"apellidos\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"raza\" class=\"form-label\">Nombres</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"nombres\"  name=\"nombres\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"raza\" class=\"form-label\">Imagen</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"imagen\"  name=\"imagen\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"nombre\" class=\"form-label\">Direccion</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"direccion\" name=\"direccion\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"fechaNacimiento\" class=\"form-label\">DNI</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"dni\" name=\"dni\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"edad\" class=\"form-label\">Telefono</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"telefono\" name=\"telefono\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"color\" class=\"form-label\">Movil</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"movil\" name=\"movil\">\r\n");
      out.write("                            </div>   \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>                        \r\n");
      out.write("                        <input id=\"inputActualizar\" type=\"submit\" name=\"Op\" value=\"Actualizar\"/>\r\n");
      out.write("                        <input id=\"inputAgregar\" type=\"submit\" name=\"Op\" value=\"Guardar\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("            /*Es para que aparezca o desaparezca los botones de agregar o actualizar p    */\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\r\n");
      out.write("                var enlaceAgregar = document.querySelector(\".Agregar\");\r\n");
      out.write("                var enlacesActualizar = document.querySelectorAll(\".Actualizar\");\r\n");
      out.write("                var inputAgregar = document.getElementById(\"inputAgregar\");\r\n");
      out.write("                var inputActualizar = document.getElementById(\"inputActualizar\");\r\n");
      out.write("                var tituloAgregar = document.getElementById(\"tituloAgregar\");\r\n");
      out.write("                var tituloEditar = document.getElementById(\"tituloEditar\");\r\n");
      out.write("\r\n");
      out.write("                //pa ocultar 1ero\r\n");
      out.write("                inputActualizar.style.display = \"none\";\r\n");
      out.write("                tituloEditar.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("                // Agregar evento clic al enlace Agregar\r\n");
      out.write("                enlaceAgregar.addEventListener(\"click\", function () {\r\n");
      out.write("                    inputActualizar.style.display = \"none\";\r\n");
      out.write("                    inputAgregar.style.display = \"block\";\r\n");
      out.write("                    tituloEditar.style.display = \"none\";\r\n");
      out.write("                    tituloAgregar.style.display = \"block\";\r\n");
      out.write("                    // Limpiar los campos del formulario\r\n");
      out.write("                    document.getElementById('idUsuario').value = \"\";\r\n");
      out.write("                    document.getElementById('contraseña').value = \"\";\r\n");
      out.write("                    document.getElementById('apellidos').value = \"\";\r\n");
      out.write("                    document.getElementById('nombres').value = \"\";\r\n");
      out.write("                    document.getElementById('imagen').value = \"\";\r\n");
      out.write("                    document.getElementById('direccion').value = \"\";\r\n");
      out.write("                    document.getElementById('dni').value = \"\";\r\n");
      out.write("                    document.getElementById('telefono').value = \"\";\r\n");
      out.write("                    document.getElementById('movil').value = \"\";\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Agregar evento clic a cada enlace Actualizar\r\n");
      out.write("                enlacesActualizar.forEach(function (enlace) {\r\n");
      out.write("                    enlace.addEventListener(\"click\", function () {\r\n");
      out.write("                        inputAgregar.style.display = \"none\";\r\n");
      out.write("                        inputActualizar.style.display = \"block\";\r\n");
      out.write("                        tituloAgregar.style.display = \"none\";\r\n");
      out.write("                        tituloEditar.style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("                        // Obtener los datos del cliente del enlace\r\n");
      out.write("                        const idUsuario = enlace.getAttribute('data-idUsuario');\r\n");
      out.write("                        const contraseña = enlace.getAttribute('data-contraseña');\r\n");
      out.write("                        const ape = enlace.getAttribute('data-ape');\r\n");
      out.write("                        const nom = enlace.getAttribute('data-nom');\r\n");
      out.write("                        const imagen = enlace.getAttribute('data-imagen');\r\n");
      out.write("                        const direc = enlace.getAttribute('data-direc');\r\n");
      out.write("                        const dni = enlace.getAttribute('data-dni');\r\n");
      out.write("                        const telef = enlace.getAttribute('data-telef');\r\n");
      out.write("                        const movil = enlace.getAttribute('data-movil');\r\n");
      out.write("\r\n");
      out.write("                        // Asignar los datos a los campos del formulario\r\n");
      out.write("                        document.getElementById('idUsuario').value = idUsuario;\r\n");
      out.write("                        document.getElementById('contraseña').value = contraseña;\r\n");
      out.write("                        document.getElementById('apellidos').value = ape;\r\n");
      out.write("                        document.getElementById('nombres').value = nom;\r\n");
      out.write("                        document.getElementById('imagen').value = imagen;\r\n");
      out.write("                        document.getElementById('direccion').value = direc;\r\n");
      out.write("                        document.getElementById('dni').value = dni;\r\n");
      out.write("                        document.getElementById('telefono').value = telef;\r\n");
      out.write("                        document.getElementById('movil').value = movil;\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function toggleSidebar() {/*Para el menu*/\r\n");
      out.write("                const sidebar1 = document.getElementById('sidebar1');\r\n");
      out.write("                const sidebar2 = document.getElementById('sidebar2');\r\n");
      out.write("                if (sidebar1.style.transform === 'translateX(-100%)') {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(0)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(-100%)';\r\n");
      out.write("                } else {\r\n");
      out.write("                    sidebar1.style.transform = 'translateX(-100%)';\r\n");
      out.write("                    sidebar2.style.transform = 'translateX(0)';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </script>    \r\n");
      out.write("        ");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <p>Tu sesión expirará en <span id=\"countdown\"></span> segundos.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("        background-color: rgb(0,0,0);\r\n");
      out.write("        background-color: rgba(0,0,0,0.4);\r\n");
      out.write("        padding-top: 60px;\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 5% auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span{\r\n");
      out.write("        font-size: 3.5vh;\r\n");
      out.write("        margin: 0.5vh;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var totalInactiveTime = 100000; // 10 segundos\r\n");
      out.write("    var warningTime = 5; // 5 segundos antes del logout\r\n");
      out.write("    var time, warningTimer;\r\n");
      out.write("\r\n");
      out.write("    window.onload = function () {\r\n");
      out.write("        resetTimer();\r\n");
      out.write("        document.addEventListener('mousemove', resetTimer, false);\r\n");
      out.write("        document.addEventListener('keypress', resetTimer, false);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function startLogoutWarning() {\r\n");
      out.write("        var countdown = warningTime;\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        var countdownElement = document.getElementById(\"countdown\");\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("        countdownElement.innerText = countdown;\r\n");
      out.write("\r\n");
      out.write("        warningTimer = setInterval(function () {\r\n");
      out.write("            countdown--;\r\n");
      out.write("            countdownElement.innerText = countdown;\r\n");
      out.write("            if (countdown < 0) {\r\n");
      out.write("                clearInterval(warningTimer);\r\n");
      out.write("                logout();\r\n");
      out.write("            }\r\n");
      out.write("        }, 1000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function logout() {\r\n");
      out.write("        alert(\"Tu sesión ha expirado.\");\r\n");
      out.write("        window.location.href = 'CerrarSesion'; /*Es el controlador que hice para que se cierre */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function resetTimer() {\r\n");
      out.write("        clearTimeout(time);\r\n");
      out.write("        clearInterval(warningTimer); // Detener el contador de advertencia si está en curso\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        modal.style.display = \"none\"; // Ocultar el modal si se muestra\r\n");
      out.write("        time = setTimeout(startLogoutWarning, (totalInactiveTime - warningTime) * 1000);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /MenuUsuarios.jsp(117,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("campo");
      // /MenuUsuarios.jsp(117,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/MenuUsuarios.jsp(117,28) '${Lista}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Lista}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <tbody>   \r\n");
            out.write("                                    <tr>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.id_usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.contraseña}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.apellidos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.nombres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.imagen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.direccion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>                                    \r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.DNI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.telefono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.movil}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.enLinea}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("                                        <td>\r\n");
            out.write("                                            <a href=\"#\" class=\"Actualizar btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\" data-idUsuario=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.id_usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-contraseña=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.contraseña}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-ape=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.apellidos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-nom=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.nombres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-imagen=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.imagen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-direc=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.direccion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-dni=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.DNI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-telef=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.telefono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-movil=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.movil}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i class=\"fas fa-edit\"></i>Actualizar</a>\r\n");
            out.write("                                        </td>\r\n");
            out.write("                                        <td>\r\n");
            out.write("                                            <a href=\"ControlerUsuario?Op=Eliminar&Id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${campo.id_usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('¿Estás seguro de que deseas eliminar este cliente?');\">\r\n");
            out.write("                                                <i class=\"fas fa-trash-alt\"></i> Eliminar\r\n");
            out.write("                                            </a>\r\n");
            out.write("                                        </td>\r\n");
            out.write("                                    </tr>        \r\n");
            out.write("                                </tbody>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
